#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/nemotron_asr/modular_nemotron_asr.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_nemotron_asr.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
from collections.abc import Callable
from dataclasses import dataclass

import torch
from torch import nn

from ... import initialization as init
from ...activations import ACT2FN
from ...generation import GenerationMode
from ...integrations import use_kernel_func_from_hub, use_kernelized_func
from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutputWithPooling
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring, can_return_tuple
from ...utils.generic import maybe_autocast, merge_with_config_defaults
from ...utils.output_capturing import capture_outputs
from ..auto import AutoModel
from .configuration_nemotron_asr import NemotronAsrConfig, NemotronAsrEncoderConfig
from .generation_nemotron_asr import (
    NemotronAsrRNNTDecoderCache,
    NemotronAsrRNNTGenerationMixin,
    NemotronAsrStreamingCache,
)


@auto_docstring(
    custom_intro="""
    Extends [~modeling_outputs.BaseModelOutputWithPooling] to include the output attention mask since sequence length
    is not preserved in the model's forward.
    """
)
@dataclass
class NemotronAsrEncoderModelOutput(BaseModelOutputWithPooling):
    r"""
    attention_mask (`torch.Tensor` of shape `(batch_size, sequence_length)`, *optional*):
        Mask to avoid performing attention on padding token indices after sequence compression. Returned because the
        sequence length may differ from the input sequence length. Mask values selected in `[0, 1]`:

        - 1 for tokens that are **not masked**,
        - 0 for tokens that are **masked**.
    """

    attention_mask: torch.Tensor | None = None


class NemotronAsrEncoderRelPositionalEncoding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: NemotronAsrEncoderConfig, device=None):
        super().__init__()
        self.max_position_embeddings = config.max_position_embeddings
        self.config = config
        inv_freq = self.compute_default_relative_positional_parameters(config, device=device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)

    @staticmethod
    def compute_default_relative_positional_parameters(
        config: NemotronAsrEncoderConfig | None = None,
        device=None,
    ) -> torch.Tensor:
        base = 10000.0
        inv_freq = 1.0 / (
            base
            ** (
                torch.arange(0, config.hidden_size, 2, dtype=torch.int64).to(device=device, dtype=torch.float)
                / config.hidden_size
            )
        )
        return inv_freq

    @torch.no_grad()
    def forward(self, hidden_states: torch.Tensor):
        seq_length = hidden_states.shape[1]
        position_ids = torch.arange(seq_length - 1, -seq_length, -1, device=hidden_states.device)
        inv_freq_expanded = (
            self.inv_freq[None, :, None].float().expand(hidden_states.shape[0], -1, 1).to(hidden_states.device)
        )
        position_ids_expanded = position_ids[None, None, :].float()

        device_type = (
            hidden_states.device.type
            if isinstance(hidden_states.device.type, str) and hidden_states.device.type != "mps"
            else "cpu"
        )
        with maybe_autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            sin = freqs.sin()
            cos = freqs.cos()
            # interleave sin and cos
            pos_embed = torch.stack([sin, cos], dim=-1)
            pos_embed = pos_embed.reshape(*pos_embed.shape[:-2], -1)

        return pos_embed.to(dtype=hidden_states.dtype)


class NemotronAsrEncoderFeedForward(nn.Module):
    def __init__(self, config: NemotronAsrEncoderConfig):
        super().__init__()
        self.linear1 = nn.Linear(config.hidden_size, config.intermediate_size, bias=config.attention_bias)
        self.activation = ACT2FN[config.hidden_act]
        self.linear2 = nn.Linear(config.intermediate_size, config.hidden_size, bias=config.attention_bias)
        self.activation_dropout = config.activation_dropout

    def forward(self, hidden_states):
        hidden_states = self.activation(self.linear1(hidden_states))
        hidden_states = nn.functional.dropout(hidden_states, p=self.activation_dropout, training=self.training)
        hidden_states = self.linear2(hidden_states)
        return hidden_states


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


@use_kernel_func_from_hub("rotary_pos_emb")
def apply_rotary_pos_emb(q, k, cos, sin, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        attn_weights = attn_weights + attention_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


@use_kernelized_func(apply_rotary_pos_emb)
class NemotronAsrEncoderAttention(nn.Module):
    """Multi-head attention with relative positional encoding. See section 3.3 of https://huggingface.co/papers/1901.02860."""

    def __init__(self, config: NemotronAsrEncoderConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = False

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )
        # W_{k,R} projection
        self.relative_k_proj = nn.Linear(config.hidden_size, config.num_attention_heads * self.head_dim, bias=False)
        # global content bias
        self.bias_u = nn.Parameter(torch.zeros(config.num_attention_heads, self.head_dim))
        # global positional bias
        self.bias_v = nn.Parameter(torch.zeros(config.num_attention_heads, self.head_dim))

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: torch.Tensor | None,
        attention_mask: torch.Tensor | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[torch.Tensor, torch.Tensor]:
        input_shape = hidden_states.shape[:-1]
        batch_size, seq_length = input_shape
        hidden_shape = (batch_size, seq_length, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        attention_interface: Callable = ALL_ATTENTION_FUNCTIONS.get_interface(
            self.config._attn_implementation, eager_attention_forward
        )

        query_states_with_bias_u = query_states + self.bias_u.view(
            1, self.config.num_attention_heads, 1, self.head_dim
        )
        query_states_with_bias_v = query_states + self.bias_v.view(
            1, self.config.num_attention_heads, 1, self.head_dim
        )

        relative_key_states = self.relative_k_proj(position_embeddings)
        relative_key_states = relative_key_states.view(batch_size, -1, self.config.num_attention_heads, self.head_dim)

        # terms (b) and (d)
        matrix_bd = query_states_with_bias_v @ relative_key_states.permute(0, 2, 3, 1)
        matrix_bd = self._rel_shift(matrix_bd)
        matrix_bd = matrix_bd[..., :seq_length]
        matrix_bd = matrix_bd * self.scaling

        if attention_mask is not None:
            # here the original codebase uses -10000.0 rather than float("-inf") and then manual masked fill with 0.0s
            # see: https://github.com/NVIDIA-NeMo/NeMo/blob/8cfedd7203462cb251a914e700e5605444277561/nemo/collections/asr/parts/submodules/multi_head_attention.py#L320-L340
            # we rather went for a straight-forward approach with float("-inf")
            matrix_bd = matrix_bd.masked_fill_(attention_mask.logical_not(), float("-inf"))

        # will compute matrix_ac - terms (a) and (c) - and add matrix_bd
        attn_output, attn_weights = attention_interface(
            self,
            query=query_states_with_bias_u,
            key=key_states,
            value=value_states,
            attention_mask=matrix_bd,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            **kwargs,
        )

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights

    def _rel_shift(self, attention_scores):
        """Relative position shift for Shaw et al. style attention. See appendix B of https://huggingface.co/papers/1901.02860."""
        batch_size, num_heads, query_length, position_length = attention_scores.shape
        # Classic view/slice/view shift, re-expressed as pad -> flatten -> narrow -> reshape: pad on
        # the left, flatten the (query, position+1) block, drop its leading `query_length` elements,
        # and re-split. Bit-identical to the original, but avoids the `-1` view inference and the
        # flatten/resplit of a product of two symbolic dims, which made torch.export emit an
        # unprovable `(2*T - 1) % T` guard on dynamic sequence length (blocking dynamic-shape export).
        attention_scores = nn.functional.pad(attention_scores, pad=(1, 0))
        attention_scores = attention_scores.flatten(-2)
        attention_scores = attention_scores.narrow(-1, query_length, query_length * position_length)
        attention_scores = attention_scores.reshape(batch_size, num_heads, query_length, position_length)
        return attention_scores

    def forward_streaming(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: torch.Tensor,
        key_value_states: torch.Tensor,
        attention_mask: torch.Tensor,
    ) -> torch.Tensor:
        """Relative-position attention with a key/value left-context cache (one streaming chunk).

        `hidden_states` are the `n` new (query) frames; `key_value_states` are `[cache, new]` of length `T2`.
        """
        batch_size, query_length = hidden_states.shape[:2]
        kv_length = key_value_states.shape[1]
        num_heads = self.config.num_attention_heads

        query_states = self.q_proj(hidden_states).view(batch_size, query_length, num_heads, self.head_dim)
        query_states = query_states.transpose(1, 2)
        key_states = (
            self.k_proj(key_value_states).view(batch_size, kv_length, num_heads, self.head_dim).transpose(1, 2)
        )
        value_states = (
            self.v_proj(key_value_states).view(batch_size, kv_length, num_heads, self.head_dim).transpose(1, 2)
        )

        query_with_bias_u = query_states + self.bias_u.view(1, num_heads, 1, self.head_dim)
        query_with_bias_v = query_states + self.bias_v.view(1, num_heads, 1, self.head_dim)

        relative_key_states = self.relative_k_proj(position_embeddings).view(batch_size, -1, num_heads, self.head_dim)
        matrix_bd = query_with_bias_v @ relative_key_states.permute(0, 2, 3, 1)
        matrix_bd = self._rel_shift(matrix_bd)[..., :kv_length]
        matrix_ac = query_with_bias_u @ key_states.transpose(-2, -1)

        scores = (matrix_ac + matrix_bd) * self.scaling
        scores = scores.masked_fill(attention_mask[:, None].logical_not(), torch.finfo(scores.dtype).min)
        attn_weights = scores.softmax(dim=-1)
        attn_output = (attn_weights @ value_states).transpose(1, 2).reshape(batch_size, query_length, -1)
        return self.o_proj(attn_output)


class NemotronAsrEncoderConvolutionModule(nn.Module):
    """Conformer convolution module for the streaming encoder.

    Differs from [`ParakeetEncoderConvolutionModule`] in two ways: the depthwise convolution is *causal* (left-padded
    by `kernel_size - 1`, no right padding) and the normalization is a `LayerNorm` over channels rather than a
    `BatchNorm1d`.
    """

    def __init__(self, config: NemotronAsrEncoderConfig):
        super().__init__()
        channels = config.hidden_size
        kernel_size = config.conv_kernel_size
        self.activation = ACT2FN[getattr(config, "hidden_act", "silu")]
        # causal depthwise conv: pad only on the left so each frame sees no future frames
        self.left_padding = kernel_size - 1

        self.pointwise_conv1 = nn.Conv1d(channels, 2 * channels, kernel_size=1, bias=config.convolution_bias)
        self.depthwise_conv = nn.Conv1d(
            channels, channels, kernel_size, padding=0, groups=channels, bias=config.convolution_bias
        )
        if config.conv_norm_type == "batch_norm":
            self.norm = nn.BatchNorm1d(channels)
        else:
            self.norm = nn.LayerNorm(channels)
        self.pointwise_conv2 = nn.Conv1d(channels, channels, kernel_size=1, bias=config.convolution_bias)

    def forward(self, hidden_states, attention_mask=None):
        hidden_states = hidden_states.transpose(1, 2)  # (B, C, T)
        hidden_states = self.pointwise_conv1(hidden_states)
        hidden_states = nn.functional.glu(hidden_states, dim=1)

        # zero out padded time steps before the (causal) depthwise conv so they don't leak into valid frames
        if attention_mask is not None:
            pad_keep = attention_mask
            if pad_keep.dim() == 4:  # (B, 1, T, T) -> (B, T) keep mask along the key axis
                pad_keep = pad_keep.any(dim=1).any(dim=1)
            hidden_states = hidden_states.masked_fill(~pad_keep[:, None, :], 0.0)

        hidden_states = nn.functional.pad(hidden_states, (self.left_padding, 0))
        hidden_states = self.depthwise_conv(hidden_states)

        if isinstance(self.norm, nn.LayerNorm):
            hidden_states = self.norm(hidden_states.transpose(1, 2)).transpose(1, 2)
        else:
            hidden_states = self.norm(hidden_states)

        hidden_states = self.activation(hidden_states)
        hidden_states = self.pointwise_conv2(hidden_states)
        return hidden_states.transpose(1, 2)

    def forward_streaming(self, hidden_states: torch.Tensor, cache: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Causal conv module for one streaming chunk, using `cache` (the previous `kernel - 1` input frames)."""
        hidden_states = hidden_states.transpose(1, 2)  # (B, C, n)
        hidden_states = self.pointwise_conv1(hidden_states)
        hidden_states = nn.functional.glu(hidden_states, dim=1)

        combined = torch.cat([cache, hidden_states], dim=-1)  # prepend cached left context instead of zero-padding
        new_cache = combined[:, :, -self.left_padding :]
        hidden_states = self.depthwise_conv(combined)

        if isinstance(self.norm, nn.LayerNorm):
            hidden_states = self.norm(hidden_states.transpose(1, 2)).transpose(1, 2)
        else:
            hidden_states = self.norm(hidden_states)
        hidden_states = self.activation(hidden_states)
        hidden_states = self.pointwise_conv2(hidden_states)
        return hidden_states.transpose(1, 2), new_cache


class NemotronAsrEncoderSubsamplingConv2D(nn.Module):
    """Causal depthwise-striding 2D convolutional subsampling (8x time reduction).

    Identical structure to [`ParakeetEncoderSubsamplingConv2D`] but with *causal* padding on both the time and
    frequency axes (`pad = (kernel - 1, stride - 1)`), matching NeMo's `causal_downsampling=True`. This changes the
    surviving frequency dimension (e.g. 128 mel bins -> 17, not 16), hence the linear projection's input width.
    """

    def __init__(self, config: NemotronAsrEncoderConfig):
        super().__init__()
        self.kernel_size = config.subsampling_conv_kernel_size
        self.stride = config.subsampling_conv_stride
        self.channels = config.subsampling_conv_channels
        self.causal = config.causal_downsampling
        self.num_layers = int(math.log2(config.subsampling_factor))

        if self.causal:
            self.left_padding = self.kernel_size - 1
            self.right_padding = self.stride - 1
        else:
            self.left_padding = self.right_padding = (self.kernel_size - 1) // 2

        self.layers = nn.ModuleList()
        self.layers.append(nn.Conv2d(1, self.channels, kernel_size=self.kernel_size, stride=self.stride, padding=0))
        self.layers.append(nn.ReLU())
        for _ in range(self.num_layers - 1):
            self.layers.append(
                nn.Conv2d(
                    self.channels,
                    self.channels,
                    kernel_size=self.kernel_size,
                    stride=self.stride,
                    padding=0,
                    groups=self.channels,
                )
            )
            self.layers.append(nn.Conv2d(self.channels, self.channels, kernel_size=1))
            self.layers.append(nn.ReLU())

        freq = config.num_mel_bins
        for _ in range(self.num_layers):
            freq = self._conv_out_length(freq)
        self.linear = nn.Linear(self.channels * freq, config.hidden_size, bias=True)

    def _conv_out_length(self, length):
        return (length + self.left_padding + self.right_padding - self.kernel_size) // self.stride + 1

    @staticmethod
    def _mask_time(hidden_states: torch.Tensor, lengths: torch.Tensor | None) -> torch.Tensor:
        # zero padded time steps (across channels and frequency) so they cannot leak into valid frames
        if lengths is None:
            return hidden_states
        time = hidden_states.shape[2]
        keep = torch.arange(time, device=hidden_states.device)[None, :] < lengths[:, None]
        return hidden_states * keep[:, None, :, None].to(hidden_states.dtype)

    def forward(self, input_features: torch.Tensor, attention_mask: torch.Tensor = None):
        hidden_states = input_features.unsqueeze(1)  # (B, 1, T, F)
        # running valid time lengths, recomputed after every strided conv (mirrors NeMo's MaskedConvSequential)
        lengths = attention_mask.sum(-1).to(torch.long) if attention_mask is not None else None

        for layer in self.layers:
            # mask padded time steps before each layer: conv biases turn padded positions non-zero, so re-mask
            hidden_states = self._mask_time(hidden_states, lengths)
            if isinstance(layer, nn.Conv2d) and layer.kernel_size[0] > 1:
                hidden_states = nn.functional.pad(
                    hidden_states,
                    (self.left_padding, self.right_padding, self.left_padding, self.right_padding),
                )
            hidden_states = layer(hidden_states)
            if isinstance(layer, nn.Conv2d) and layer.stride[0] > 1 and lengths is not None:
                lengths = self._conv_out_length(lengths)
        hidden_states = self._mask_time(hidden_states, lengths)

        hidden_states = hidden_states.transpose(1, 2).reshape(hidden_states.shape[0], hidden_states.shape[2], -1)
        hidden_states = self.linear(hidden_states)
        return hidden_states


class NemotronAsrEncoderBlock(GradientCheckpointingLayer):
    def __init__(self, config: NemotronAsrEncoderConfig, layer_idx: int | None = None):
        super().__init__()
        self.gradient_checkpointing = False

        self.feed_forward1 = NemotronAsrEncoderFeedForward(config)
        self.self_attn = NemotronAsrEncoderAttention(config, layer_idx)
        self.conv = NemotronAsrEncoderConvolutionModule(config)
        self.feed_forward2 = NemotronAsrEncoderFeedForward(config)

        self.norm_feed_forward1 = nn.LayerNorm(config.hidden_size)
        self.norm_self_att = nn.LayerNorm(config.hidden_size)
        self.norm_conv = nn.LayerNorm(config.hidden_size)
        self.norm_feed_forward2 = nn.LayerNorm(config.hidden_size)
        self.norm_out = nn.LayerNorm(config.hidden_size)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        position_embeddings: torch.Tensor | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        residual = hidden_states
        hidden_states = self.feed_forward1(self.norm_feed_forward1(hidden_states))
        hidden_states = residual + 0.5 * hidden_states  # the conformer architecture uses a factor of 0.5

        normalized_hidden_states = self.norm_self_att(hidden_states)
        attn_output, _ = self.self_attn(
            hidden_states=normalized_hidden_states,
            attention_mask=attention_mask,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = hidden_states + attn_output

        conv_output = self.conv(self.norm_conv(hidden_states), attention_mask=attention_mask)
        hidden_states = hidden_states + conv_output

        ff2_output = self.feed_forward2(self.norm_feed_forward2(hidden_states))
        hidden_states = hidden_states + 0.5 * ff2_output  # the conformer architecture uses a factor of 0.5

        hidden_states = self.norm_out(hidden_states)

        return hidden_states


@auto_docstring
class NemotronAsrPreTrainedModel(PreTrainedModel):
    config: NemotronAsrConfig
    base_model_prefix = "model"
    main_input_name = "input_features"
    input_modalities = "audio"
    supports_gradient_checkpointing = True
    _no_split_modules = ["NemotronAsrEncoderBlock"]
    _supports_flat_attention_mask = True
    _supports_sdpa = True
    _supports_flex_attn = True

    # TODO: @eustlb, add support when flash attention supports custom attention bias
    _supports_flash_attn = False

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "hidden_states": NemotronAsrEncoderBlock,
        "attentions": NemotronAsrEncoderAttention,
    }

    @torch.no_grad()
    def _init_weights(self, module):
        super()._init_weights(module)
        std = getattr(self.config, "initializer_range", 0.02)

        if isinstance(module, NemotronAsrEncoderAttention):
            init.normal_(module.bias_u, mean=0.0, std=std)
            init.normal_(module.bias_v, mean=0.0, std=std)
        elif isinstance(module, NemotronAsrEncoderRelPositionalEncoding):
            buffer_value = module.compute_default_relative_positional_parameters(module.config)
            init.copy_(module.inv_freq, buffer_value)

    def _get_subsampling_output_length(self, input_lengths: torch.Tensor):
        encoder_config = getattr(self.config, "encoder_config", self.config)
        kernel_size = encoder_config.subsampling_conv_kernel_size
        stride = encoder_config.subsampling_conv_stride
        num_layers = int(math.log2(encoder_config.subsampling_factor))

        if encoder_config.causal_downsampling:
            all_paddings = (kernel_size - 1) + (stride - 1)
        else:
            all_paddings = (kernel_size - 1) // 2 * 2
        add_pad = all_paddings - kernel_size

        lengths = input_lengths
        for _ in range(num_layers):
            lengths = torch.floor(torch.div(lengths.to(dtype=torch.float) + add_pad, stride) + 1.0)
        return lengths.to(dtype=torch.int)

    def _get_output_attention_mask(self, attention_mask: torch.Tensor, target_length: int | None = None):
        """
        Convert the input attention mask to its subsampled form. `target_length` sets the desired output length, useful
        when the attention mask length differs from `sum(-1).max()` (i.e., when the longest sequence in the batch is padded)
        """
        output_lengths = self._get_subsampling_output_length(attention_mask.sum(-1))
        # Use target_length if provided, otherwise use max length in batch
        max_length = target_length if target_length is not None else output_lengths.max()
        attention_mask = torch.arange(max_length, device=attention_mask.device) < output_lengths[:, None]
        return attention_mask


def build_chunked_limited_mask(
    att_context_size, seq_length: int, device, style: str = "chunked_limited"
) -> torch.Tensor:
    """Boolean *keep* mask of shape `(seq_length, seq_length)` where `True` means query *i* attends to key *j*.

    Mirrors NeMo's `ConformerEncoder._create_masks`. For `chunked_limited`, frames are grouped into
    non-overlapping chunks of size `right + 1`; chunk `c` attends to its own chunk and `left // (right + 1)` chunks
    to the left.
    """
    left, right = int(att_context_size[0]), int(att_context_size[1])
    idx = torch.arange(seq_length, device=device)

    if style == "chunked_limited" and right != -1:
        chunk_size = right + 1
        left_chunks = left // chunk_size if left >= 0 else 10000
        chunk_idx = torch.div(idx, chunk_size, rounding_mode="trunc")
        diff = chunk_idx.unsqueeze(1) - chunk_idx.unsqueeze(0)
        return torch.logical_and(diff >= 0, diff <= left_chunks)

    # regular sliding window (and unlimited-right fallback)
    diff = idx.unsqueeze(1) - idx.unsqueeze(0)  # i - j
    keep = torch.ones(seq_length, seq_length, dtype=torch.bool, device=device)
    if left >= 0:
        keep = torch.logical_and(keep, diff <= left)
    if right >= 0:
        keep = torch.logical_and(keep, diff >= -right)
    return keep


@auto_docstring(
    custom_intro="""
    The Nemotron 3.5 ASR cache-aware streaming FastConformer encoder.
    """
)
class NemotronAsrEncoder(NemotronAsrPreTrainedModel):
    config: NemotronAsrEncoderConfig
    base_model_prefix = "encoder"

    def __init__(self, config: NemotronAsrEncoderConfig):
        super().__init__(config)
        self.config = config
        self.gradient_checkpointing = False

        self.dropout = config.dropout
        self.dropout_positions = config.dropout_positions
        self.layerdrop = config.layerdrop

        self.input_scale = math.sqrt(config.hidden_size) if config.scale_input else 1.0
        self.subsampling = NemotronAsrEncoderSubsamplingConv2D(config)
        self.encode_positions = NemotronAsrEncoderRelPositionalEncoding(config)
        self.layers = nn.ModuleList(
            [NemotronAsrEncoderBlock(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.post_init()

    @auto_docstring
    @merge_with_config_defaults
    @capture_outputs
    @can_return_tuple
    def forward(
        self,
        input_features: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        output_attention_mask: bool = True,
        **kwargs: Unpack[TransformersKwargs],
    ) -> NemotronAsrEncoderModelOutput:
        r"""
        output_attention_mask (`bool`, *optional*, defaults to `True`):
            Whether to return the subsampled attention mask. Only effective when `attention_mask` is provided.
        """
        hidden_states = self.subsampling(input_features, attention_mask)
        hidden_states = hidden_states * self.input_scale
        position_embeddings = self.encode_positions(hidden_states)

        hidden_states = nn.functional.dropout(hidden_states, p=self.dropout, training=self.training)
        position_embeddings = nn.functional.dropout(
            position_embeddings, p=self.dropout_positions, training=self.training
        )

        seq_length = hidden_states.shape[1]
        # limited, chunked context applies regardless of padding
        band_mask = build_chunked_limited_mask(
            self.config.att_context_size, seq_length, hidden_states.device, self.config.att_context_style
        )

        output_mask = None
        if attention_mask is not None:
            output_mask = self._get_output_attention_mask(attention_mask, target_length=seq_length)
            pad_mask = output_mask.unsqueeze(1).expand(-1, seq_length, -1)
            pad_mask = pad_mask & pad_mask.transpose(1, 2)
            attention_mask = (pad_mask & band_mask.unsqueeze(0)).unsqueeze(1)
        else:
            attention_mask = band_mask.view(1, 1, seq_length, seq_length)

        for encoder_layer in self.layers:
            to_drop = self.training and torch.rand([]) < self.layerdrop
            if not to_drop:
                hidden_states = encoder_layer(
                    hidden_states,
                    attention_mask=attention_mask,
                    position_embeddings=position_embeddings,
                    **kwargs,
                )

        return NemotronAsrEncoderModelOutput(
            last_hidden_state=hidden_states,
            attention_mask=output_mask.int() if output_mask is not None and output_attention_mask else None,
        )

    @property
    def streaming_config(self) -> dict:
        """Derived cache-aware streaming sizes for the configured `att_context_size` (all in 80 ms encoder frames,
        except mel sizes). Mirrors NeMo's `ConformerEncoder.setup_streaming_params` for the `chunked_limited` style.
        """
        config = self.config
        chunk = config.att_context_size[1] + 1
        subsampling_factor = config.subsampling_factor
        pre_encode_frames = subsampling_factor + 1
        return {
            "last_channel_cache_size": config.att_context_size[0],
            "conv_cache_size": config.conv_kernel_size - 1,
            "chunk_frames": chunk,  # subsampled output frames emitted per step
            "left_chunks": config.att_context_size[0] // chunk,
            "valid_out_len": chunk,
            "pre_encode_frames": pre_encode_frames,
            "drop_extra_pre_encoded": 1 + (pre_encode_frames - 1) // subsampling_factor,
            "chunk_mel": chunk * subsampling_factor,
            "first_chunk_mel": chunk * subsampling_factor - (subsampling_factor - 1),
        }

    def _build_streaming_attention_mask(self, query_length: int, valid_cache_len: int, device) -> torch.Tensor:
        """Chunked-limited keep-mask `(1, query_length, cache + query_length)` for one streaming chunk.

        The new (query) frames sit at the end of the `[cache, new]` sequence; unfilled cache slots are masked out.
        """
        scfg = self.streaming_config
        cache_size, chunk, left_chunks = scfg["last_channel_cache_size"], scfg["chunk_frames"], scfg["left_chunks"]
        kv_length = cache_size + query_length
        idx = torch.arange(kv_length, device=device)
        chunk_idx = torch.div(idx, chunk, rounding_mode="trunc")
        diff = chunk_idx[:, None] - chunk_idx[None, :]
        band = (diff >= 0) & (diff <= left_chunks)
        valid_keys = idx >= (cache_size - valid_cache_len)  # ignore not-yet-filled cache positions
        keep = band & valid_keys[None, :]
        return keep[cache_size:].unsqueeze(0)

    def streaming_forward(
        self,
        input_features: torch.Tensor,
        last_channel: list[torch.Tensor],
        last_time: list[torch.Tensor],
        last_channel_len: int,
        drop_extra_pre_encoded: int,
    ) -> tuple[torch.Tensor, list[torch.Tensor], list[torch.Tensor], int]:
        """Run the cache-aware encoder on one chunk of (already left-padded) mel features.

        Returns the chunk embeddings `(batch, valid_out_len, hidden)` and the updated per-layer caches. This is the
        numerical equivalent of NeMo's `ConformerEncoder.cache_aware_stream_step` for the `chunked_limited` style.
        """
        scfg = self.streaming_config
        cache_size = scfg["last_channel_cache_size"]

        hidden_states = self.subsampling(input_features)
        hidden_states = hidden_states[:, drop_extra_pre_encoded:]
        hidden_states = hidden_states * self.input_scale
        query_length = hidden_states.shape[1]

        position_embeddings = self.encode_positions(
            hidden_states.new_zeros(hidden_states.shape[0], query_length + cache_size, hidden_states.shape[2])
        )
        attention_mask = self._build_streaming_attention_mask(query_length, last_channel_len, hidden_states.device)

        new_channel, new_time = [], []
        for i, layer in enumerate(self.layers):
            hidden_states = hidden_states + 0.5 * layer.feed_forward1(layer.norm_feed_forward1(hidden_states))
            normed = layer.norm_self_att(hidden_states)
            key_value_states = torch.cat([last_channel[i], normed], dim=1) if last_channel[i].shape[1] else normed
            attn_output = layer.self_attn.forward_streaming(
                normed, position_embeddings, key_value_states, attention_mask
            )
            new_channel.append(key_value_states[:, -cache_size:])
            hidden_states = hidden_states + attn_output

            conv_output, conv_cache = layer.conv.forward_streaming(layer.norm_conv(hidden_states), last_time[i])
            new_time.append(conv_cache)
            hidden_states = hidden_states + conv_output

            hidden_states = hidden_states + 0.5 * layer.feed_forward2(layer.norm_feed_forward2(hidden_states))
            hidden_states = layer.norm_out(hidden_states)

        hidden_states = hidden_states[:, : scfg["valid_out_len"]]
        next_cache_len = min(last_channel_len + query_length, cache_size)
        return hidden_states, new_channel, new_time, next_cache_len


class NemotronAsrRNNTDecoder(nn.Module):
    """LSTM-based prediction network For RNN-T"""

    def __init__(self, config: NemotronAsrConfig):
        super().__init__()
        self.blank_token_id = config.blank_token_id
        self.embedding = nn.Embedding(config.vocab_size, config.decoder_hidden_size)
        self.lstm = nn.LSTM(
            input_size=config.decoder_hidden_size,
            hidden_size=config.decoder_hidden_size,
            num_layers=config.num_decoder_layers,
            batch_first=True,
        )
        self.decoder_projector = nn.Linear(config.decoder_hidden_size, config.decoder_hidden_size)

    def forward(
        self,
        input_ids: torch.LongTensor,
        cache: NemotronAsrRNNTDecoderCache | None = None,
    ) -> torch.Tensor:
        if cache is not None:
            blank_mask = input_ids[:, -1] == self.blank_token_id
            # All-blank fast path: skip decoder when all batch elements predict blank
            if cache.is_initialized and blank_mask.all():
                return cache.cache

        embeddings = self.embedding(input_ids)

        # Get cached hidden/cell states if available, otherwise initialize with NemotronAsrRNNTDecoderCache
        if cache is not None:
            was_initialized = cache.is_initialized
            if not was_initialized:
                cache.lazy_initialization(embeddings)
            hidden_cell_states = (cache.hidden_state, cache.cell_state)
        else:
            hidden_cell_states = None

        lstm_output, (hidden_state, cell_state) = self.lstm(embeddings, hidden_cell_states)
        decoder_output = self.decoder_projector(lstm_output)

        if cache is not None:
            mask = ~blank_mask if was_initialized else None
            cache.update(decoder_output, hidden_state, cell_state, mask=mask)
            return cache.cache

        return decoder_output


class NemotronAsrRNNTJointNetwork(nn.Module):
    """Joint network that combines encoder and decoder outputs to predict token logits."""

    def __init__(self, config: NemotronAsrConfig):
        super().__init__()
        self.activation = ACT2FN[config.hidden_act]
        self.head = nn.Linear(config.decoder_hidden_size, config.vocab_size)
        self.vocab_size = config.vocab_size

    def forward(
        self,
        decoder_hidden_states: torch.Tensor,
        encoder_hidden_states: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        joint_output = self.activation(encoder_hidden_states + decoder_hidden_states)
        return self.head(joint_output)


@dataclass
class NemotronAsrRNNTOutput(BaseModelOutputWithPooling):
    """
    Output of the NemotronAsr RNN-T forward pass.

    Args:
        loss (`torch.FloatTensor`, *optional*):
            RNN-T loss, returned when `labels` are provided.
        logits (`torch.FloatTensor`):
            Joint token logits. Shape is `(batch, T, U+1, vocab)` for training
            or `(batch, 1, 1, vocab)` for single-step inference.
        decoder_cache (`NemotronAsrRNNTDecoderCache`, *optional*):
            Decoder LSTM cache containing hidden state, cell state, and last output.
    """

    loss: torch.FloatTensor | None = None
    logits: torch.FloatTensor | None = None
    decoder_cache: NemotronAsrRNNTDecoderCache | None = None


@auto_docstring(
    custom_intro="""
    Nemotron 3.5 ASR: a prompt-conditioned cache-aware streaming FastConformer encoder with an RNN-T head.

    A one-hot language prompt (selected by `prompt_indices`) is broadcast across time, concatenated to the encoder
    output, and projected back to `hidden_size` by `prompt_kernel` before the RNN-T joint network.
    """
)
class NemotronAsrForRNNT(NemotronAsrPreTrainedModel, NemotronAsrRNNTGenerationMixin):
    config: NemotronAsrConfig
    _no_split_modules = ["NemotronAsrEncoderBlock", "NemotronAsrRNNTDecoder"]
    _supported_generation_modes = [GenerationMode.GREEDY_SEARCH]

    def __init__(self, config: NemotronAsrConfig):
        super().__init__(config)
        self.encoder = AutoModel.from_config(config.encoder_config)
        self.encoder_projector = nn.Linear(config.encoder_config.hidden_size, config.decoder_hidden_size)
        self.decoder = NemotronAsrRNNTDecoder(config)
        self.joint = NemotronAsrRNNTJointNetwork(config)
        self.max_symbols_per_step = config.max_symbols_per_step
        self.num_prompts = config.num_prompts
        # prompt_kernel: concat(encoder_out, one_hot_lang) -> MLP -> back to hidden_size
        self.prompt_kernel = nn.Sequential(
            nn.Linear(config.encoder_config.hidden_size + config.num_prompts, config.encoder_config.hidden_size * 2),
            nn.ReLU(),
            nn.Linear(config.encoder_config.hidden_size * 2, config.encoder_config.hidden_size),
        )

        self.post_init()

    @can_return_tuple
    def get_audio_features(
        self,
        input_features: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        prompt_indices: torch.Tensor | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> NemotronAsrEncoderModelOutput:
        encoder_outputs = self.encoder(input_features=input_features, attention_mask=attention_mask, **kwargs)
        hidden_states = encoder_outputs.last_hidden_state
        if prompt_indices is not None:
            hidden_states = self._apply_prompt(hidden_states, prompt_indices)
        encoder_outputs.last_hidden_state = hidden_states
        encoder_outputs.pooler_output = self.encoder_projector(hidden_states)
        return encoder_outputs

    @auto_docstring
    @can_return_tuple
    def forward(
        self,
        input_features: torch.Tensor | None = None,
        attention_mask: torch.Tensor | None = None,
        prompt_indices: torch.Tensor | None = None,
        decoder_input_ids: torch.LongTensor | None = None,
        decoder_cache=None,
        use_decoder_cache: bool | None = None,
        encoder_outputs: NemotronAsrEncoderModelOutput | tuple[torch.FloatTensor] | None = None,
        labels: torch.Tensor | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> NemotronAsrRNNTOutput:
        r"""
        prompt_indices (`torch.LongTensor` of shape `(batch_size,)`, *optional*):
            Language-ID prompt index per batch element (see `config.prompt_dictionary`). Selects the one-hot language
            vector fused with the encoder output. Required to reproduce the multilingual behavior of the model.
        decoder_cache (`NemotronAsrRNNTDecoderCache`, *optional*):
            Decoder LSTM cache. When provided and initialized, the cached `decoder_output` is reused (e.g. during
            blank-skipping) instead of running the decoder.
        use_decoder_cache (`bool`, *optional*):
            Whether to use a decoder cache. When `True` and `decoder_cache` is `None`, a new cache is created.
        """
        if encoder_outputs is None:
            encoder_outputs = self.get_audio_features(
                input_features=input_features,
                attention_mask=attention_mask,
                prompt_indices=prompt_indices,
                **kwargs,
            )
        if encoder_outputs is None:
            encoder_outputs = self.get_audio_features(
                input_features=input_features,
                attention_mask=attention_mask,
                **kwargs,
            )

        if use_decoder_cache and decoder_cache is None:
            decoder_cache = NemotronAsrRNNTDecoderCache(self.config)

        decoder_hidden_states = self.decoder(decoder_input_ids, cache=decoder_cache)
        logits = self.joint(
            encoder_hidden_states=encoder_outputs.pooler_output[:, :, None, :],
            decoder_hidden_states=decoder_hidden_states[:, None, :, :],
        ).squeeze(2)

        loss = None
        if labels is not None:
            logit_lengths = encoder_outputs.attention_mask.sum(-1)
            loss = self.loss_function(
                logits=logits[:, : int(logit_lengths.max())],
                labels=labels,
                logit_lengths=logit_lengths,
                label_lengths=(labels != self.config.blank_token_id).sum(-1),
                blank_token_id=self.config.blank_token_id,
                **kwargs,
            )

        return NemotronAsrRNNTOutput(
            loss=loss,
            logits=logits,
            last_hidden_state=encoder_outputs.last_hidden_state,
            pooler_output=encoder_outputs.pooler_output,
            hidden_states=encoder_outputs.hidden_states,
            attentions=encoder_outputs.attentions,
            decoder_cache=decoder_cache,
        )

    def _apply_prompt(self, encoder_hidden_states: torch.Tensor, prompt_indices: torch.Tensor) -> torch.Tensor:
        batch_size, seq_length, _ = encoder_hidden_states.shape
        prompt = torch.zeros(
            batch_size,
            seq_length,
            self.num_prompts,
            dtype=encoder_hidden_states.dtype,
            device=encoder_hidden_states.device,
        )
        prompt.scatter_(2, prompt_indices.view(batch_size, 1, 1).expand(-1, seq_length, -1).long(), 1.0)
        fused = torch.cat([encoder_hidden_states, prompt], dim=-1)
        return self.prompt_kernel(fused)

    # ----- cache-aware streaming inference -----

    def init_streaming_state(self, batch_size: int = 1, device=None, dtype=None) -> NemotronAsrStreamingCache:
        """Create an empty [`NemotronAsrStreamingCache`] for cache-aware streaming inference."""
        device = device if device is not None else next(self.parameters()).device
        dtype = dtype if dtype is not None else next(self.parameters()).dtype
        encoder_config = self.config.encoder_config
        scfg = self.encoder.streaming_config
        hidden_size = encoder_config.hidden_size
        decoder_cache = NemotronAsrRNNTDecoderCache(self.config)
        return NemotronAsrStreamingCache(
            # full-size channel caches; the streaming mask ignores the not-yet-filled (zero) left part
            last_channel=[
                torch.zeros(batch_size, scfg["last_channel_cache_size"], hidden_size, device=device, dtype=dtype)
                for _ in range(encoder_config.num_hidden_layers)
            ],
            last_time=[
                torch.zeros(batch_size, hidden_size, scfg["conv_cache_size"], device=device, dtype=dtype)
                for _ in range(encoder_config.num_hidden_layers)
            ],
            last_channel_len=0,
            pre_encode=torch.zeros(batch_size, 0, encoder_config.num_mel_bins, device=device, dtype=dtype),
            decoder_cache=decoder_cache,
            last_token=torch.full((batch_size, 1), self.config.blank_token_id, device=device, dtype=torch.long),
        )

    @torch.no_grad()
    def _streaming_decode(self, encoder_frames: torch.Tensor, cache: NemotronAsrStreamingCache) -> list[list[int]]:
        """Greedy RNN-T decode of one chunk of (projected) encoder frames, carrying the decoder state in `cache`."""
        blank_token_id = self.config.blank_token_id
        batch_size, num_frames = encoder_frames.shape[0], encoder_frames.shape[1]
        if not cache.decoder_cache.is_initialized:
            self.decoder(cache.last_token, cache=cache.decoder_cache)  # g_0 for the start (blank) token

        emitted: list[list[int]] = [[] for _ in range(batch_size)]
        for t in range(num_frames):
            encoder_step = encoder_frames[:, t]  # (batch, decoder_hidden)
            for _ in range(self.max_symbols_per_step):
                logits = self.joint(
                    encoder_hidden_states=encoder_step[:, None, None, :],
                    decoder_hidden_states=cache.decoder_cache.cache[:, None, :, :],
                ).reshape(batch_size, -1)
                tokens = logits.argmax(dim=-1)
                if bool((tokens == blank_token_id).all()):
                    break
                for b in range(batch_size):
                    if int(tokens[b]) != blank_token_id:
                        emitted[b].append(int(tokens[b]))
                # advance the prediction network for non-blank emissions (blank elements are masked, state frozen)
                self.decoder(tokens[:, None], cache=cache.decoder_cache)
                cache.last_token = tokens[:, None]
        return emitted

    @torch.no_grad()
    def streaming_step(
        self,
        input_features: torch.Tensor,
        cache: NemotronAsrStreamingCache,
        prompt_indices: torch.Tensor | None = None,
        drop_extra_pre_encoded: int = 0,
    ) -> tuple[list[list[int]], NemotronAsrStreamingCache]:
        """Process one chunk of mel features (already left-padded with `cache.pre_encode`) and emit RNN-T tokens.

        Returns the per-batch list of newly emitted token ids and the updated `cache`.
        """
        embeddings, cache.last_channel, cache.last_time, cache.last_channel_len = self.encoder.streaming_forward(
            input_features, cache.last_channel, cache.last_time, cache.last_channel_len, drop_extra_pre_encoded
        )
        if prompt_indices is not None:
            embeddings = self._apply_prompt(embeddings, prompt_indices)
        encoder_frames = self.encoder_projector(embeddings)
        tokens = self._streaming_decode(encoder_frames, cache)
        return tokens, cache

    @torch.no_grad()
    def transcribe_stream(
        self,
        input_features: torch.Tensor,
        prompt_indices: torch.Tensor | None = None,
    ) -> list[list[int]]:
        """Convenience driver: split `input_features` into cache-aware streaming chunks and return emitted token ids.

        This reproduces NeMo's chunk schedule for the `chunked_limited` style (first chunk shorter, subsequent chunks
        left-padded by `pre_encode_frames`), so the output is identical to a real per-chunk stream.
        """
        scfg = self.encoder.streaming_config
        pre, chunk_mel, first_mel = scfg["pre_encode_frames"], scfg["chunk_mel"], scfg["first_chunk_mel"]
        drop = scfg["drop_extra_pre_encoded"]
        total = input_features.shape[1]

        cache = self.init_streaming_state(input_features.shape[0], input_features.device, input_features.dtype)
        emitted: list[list[int]] = [[] for _ in range(input_features.shape[0])]
        pos, step = 0, 0
        while pos < total:
            if step == 0:
                window, cur_drop = input_features[:, :first_mel], 0
                pos = first_mel
            else:
                end = min(pos + chunk_mel, total)
                window, cur_drop = input_features[:, pos - pre : end], drop
                pos = end
            tokens, cache = self.streaming_step(window, cache, prompt_indices, cur_drop)
            for b in range(len(emitted)):
                emitted[b].extend(tokens[b])
            step += 1
        return emitted


__all__ = ["NemotronAsrForRNNT", "NemotronAsrEncoder", "NemotronAsrPreTrainedModel"]
